<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NbnBotClean.Infrastructure</RootNamespace>
    <AssemblyName>NbnBotClean.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Migrations\NbnBotDb\**" />
    <EmbeddedResource Remove="Data\Migrations\NbnBotDb\**" />
    <None Remove="Data\Migrations\NbnBotDb\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="EFCore.BulkExtensions.SqlServer" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\Seed\ServiceClasses.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
</Project>
